version: '3.8'

services:
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - published: 8080
        target: 80
        protocol: tcp
        mode: ingress

